import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circularContainer: {
    height: 200,
    width: 200,
    backgroundColor: 'grey',
    borderRadius: 200 / 2,
    borderWidth: 15,
    borderColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  label: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  buttonContainer: {
    height: 100,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    borderTopColor: 'white',
    backgroundColor: 'grey',
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  button: {
    height: 50,
    width: 200,
    backgroundColor: 'grey',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemStyle: {
    backgroundColor: 'grey',
    margin: 10,
    height: 50,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    borderColor: 'black',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  remove: {
    color: 'white',
    margin: 5,
  },
  row: {
    flexDirection: 'row',
  },
  flatList: {
    width: '100%',
    marginTop: 20,
  },
  linethrough: {
    textDecorationLine: 'line-through',
    textDecorationColor: 'red',
  },
  message: {
    flex: 1,
    alignItems: 'center',
    marginTop: 50,
  },
  headerStyles: {
    backgroundColor: 'grey',
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
});

export default styles;
